ALTER TABLE "activity_events" DROP CONSTRAINT "activity_events_event_type_check";--> statement-breakpoint
DROP INDEX "saved_work_views_personal_name_unique";--> statement-breakpoint
DROP INDEX "saved_work_views_workspace_name_unique";--> statement-breakpoint
ALTER TABLE "saved_work_views" ADD COLUMN "project_id" uuid;--> statement-breakpoint
ALTER TABLE "saved_work_views" ADD COLUMN "scope" text DEFAULT 'workspace' NOT NULL;--> statement-breakpoint
ALTER TABLE "saved_work_views" ADD CONSTRAINT "saved_work_views_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "saved_work_views_workspace_scope_updated_idx" ON "saved_work_views" USING btree ("workspace_id","scope","updated_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "saved_work_views_project_scope_updated_idx" ON "saved_work_views" USING btree ("workspace_id","project_id","scope","updated_at" DESC NULLS LAST) WHERE "saved_work_views"."scope" = 'project';--> statement-breakpoint
CREATE UNIQUE INDEX "saved_work_views_workspace_personal_name_unique" ON "saved_work_views" USING btree ("workspace_id","owner_member_id",lower("name")) WHERE "saved_work_views"."scope" = 'workspace' and "saved_work_views"."visibility" = 'personal';--> statement-breakpoint
CREATE UNIQUE INDEX "saved_work_views_workspace_shared_name_unique" ON "saved_work_views" USING btree ("workspace_id",lower("name")) WHERE "saved_work_views"."scope" = 'workspace' and "saved_work_views"."visibility" = 'workspace';--> statement-breakpoint
CREATE UNIQUE INDEX "saved_work_views_project_personal_name_unique" ON "saved_work_views" USING btree ("workspace_id","project_id","owner_member_id",lower("name")) WHERE "saved_work_views"."scope" = 'project' and "saved_work_views"."visibility" = 'personal';--> statement-breakpoint
CREATE UNIQUE INDEX "saved_work_views_project_shared_name_unique" ON "saved_work_views" USING btree ("workspace_id","project_id",lower("name")) WHERE "saved_work_views"."scope" = 'project' and "saved_work_views"."visibility" = 'workspace';--> statement-breakpoint
ALTER TABLE "activity_events" ADD CONSTRAINT "activity_events_event_type_check" CHECK (event_type in ('project.name_changed', 'project.description_changed', 'project.archived', 'project.reactivated', 'milestone.created', 'milestone.name_changed', 'milestone.description_changed', 'milestone.status_changed', 'milestone.target_date_changed', 'milestone.archived', 'milestone.reactivated', 'label.created', 'label.name_changed', 'label.color_changed', 'label.archived', 'label.reactivated', 'work_item.created', 'work_item.title_changed', 'work_item.description_changed', 'work_item.status_changed', 'work_item.assignee_changed', 'work_item.priority_changed', 'work_item.milestone_changed', 'work_item.label_added', 'work_item.label_removed', 'work_item.relationship_added', 'work_item.relationship_removed', 'saved_view.created', 'saved_view.name_changed', 'saved_view.query_changed', 'saved_view.updated', 'saved_view.deleted', 'comment.added', 'comment.edited', 'comment.deleted'));--> statement-breakpoint
ALTER TABLE "saved_work_views" ADD CONSTRAINT "saved_work_views_scope_check" CHECK (scope in ('workspace', 'project'));--> statement-breakpoint
ALTER TABLE "saved_work_views" ADD CONSTRAINT "saved_work_views_scope_project_check" CHECK ((("saved_work_views"."scope" = 'workspace' and "saved_work_views"."project_id" is null) or ("saved_work_views"."scope" = 'project' and "saved_work_views"."project_id" is not null)));